name: test

on:
  pull_request:
  push:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install pytest
      - run: make unit

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install pytest coverage
      - run: make coverage

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install flake8 flake8-import-order codespell
      - run: make lint

  installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install .
      - run: make installation-tests

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: make nix-tests
